server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer-register
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers
            - Method=POST
        - id: customer-login
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/login
            - Method=POST
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
            - Header=Authorization, Bearer (.*)
          filters:
            - AuthorizationHeaderFilter
        - id: account-management
          uri: lb://ACCOUNT-MANAGEMENT
          predicates:
            - Path=/api/v1/account/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


token:
  secret: rlacndgusrlacndgusrlacndgus151515
